

####
server:
  port: 8081

spring:
  application:
    name: demo-server-01
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
  path: ./target
  file: eureka-server.log


project:
  report:
    server-name: report-server
    hosts:
      - host: 192.168.1.11
        port: 8080
      - host: 192.168.2.11
        port: 8081
      - host: 192.168.3.33
        port: 8801

