############################### 本地测试配置 ##################################
spring:
  profiles: pre
  kafka:
    producer:
      bootstrap-servers:
        - 172.16.16.8:9092
        - 172.16.16.9:9092
        - 172.16.16.10:9092
    consumer:
      bootstrap-servers:
        - 172.16.16.8:9092
        - 172.16.16.9:9092
        - 172.16.16.10:9092
      group-id: netty-server-${my.server.id}
      auto-offset-reset: latest #  latest, earliest, none
  redis:
#    host: 40.73.24.131
#    password: sinogold
#    port: 6379
    cluster:
      nodes:
        - 172.16.16.4:6379
        - 172.16.16.4:6380
        - 172.16.16.5:6379
        - 172.16.16.5:6380
        - 172.16.16.7:6379
        - 172.16.16.7:6380
  data:
    mongodb:
      uri: mongodb://172.16.16.8:20000,172.16.16.9:20000,172.16.16.10:20000/sinogold
#      port: 27018
#      host: 40.73.24.131
#      database: sinogold
#  rabbitmq:
#    host: 192.168.88.174
#    port: 5672
#    username: guest
#    password: guest
mqtt:
#  host: tcp://40.73.24.131:1883
  host: tcp://172.16.16.6:1883
  clientId: 119
  username: 110
  password: futuremove
  model: single
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
#      defaultZone: http://www.zscaling.xin:10035/eureka/
      defaultZone: http://172.16.16.4:8761/eureka/,http://172.16.16.5:8761/eureka/
zookeeper:
  id: 9
  url: 172.16.16.8:2181,172.16.16.9:2181,172.16.16.10:2181
  namespace: sinogold
  masterPath: /master
  configPath: /config
  serversPath: /servers
activeLink:
  kafka:
    topic:
      otaUpgrade: ota-upgrade
      otaStatus: ota-status

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: false
    prometheus:
      id: springmetrics
  endpoint:
    beans:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true
      show-details: always
    mappings:
      enabled: true
    info:
      enabled: true
    hystrix:
      stream:
        enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enable: true
        step: 1m
        descriptions: true
  security:
    user:
      name: chengchao
      password: sinogold%202018