eureka:
  instance:
    prefer-ip-address: true # 将自己的 IP 注册到 Eureka Server 上面。
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

turbine:
  appConfig: my-ribbons
  clusterNameExpression: "'default'"
#console-available: true

spring:
  profiles: dev
  http:
    multipart:
    maxFileSize:  10Mb
    maxRequestSize: 100Mb
#  output:
#    ansi:
#      enabled: ALWAYS


