spring:
  application:
    name: tbox-gateway
  profiles:
    active: @project.env@
server:
  port: 8224
  servlet:
    context-path: /tbox-gateway
logging:
  path: targtet/logs/
  file: logs/tbox-gateway.out
  level:
    com.sinogold: info
project:
  ip-address: 192.168.0.110