

####
server:
  port: 18082

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ribbon-server-2
  cloud:
    consul:
      host: 192.168.56.102
      port: 8500
      discovery:
        prefer-ip-address: true
