
server:
  port: 8083
spring:
  application:
    name: my-scala003
  cloud:
    service-registry:
      auto-registration:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
