

####
server:
  port: 8082

spring:
  application:
    name: demo-client-01
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
  path: ./target
  file: eureka-server.log