
server:
  port: 8084
spring:
  application:
    name: my-spring-boot-admin
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8080
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS