
spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false # 是否开启自我保护，默认： true
    eviction-interval-timer-in-ms: 5000
    use-read-only-response-cache: false

logging:
  level:
    root: INFO
  file:
    path: ./target/