
spring:
  profiles: local_dev
#热部署生效
  devtools:
    restart:
      enabled: true
server:
  port: 10080 # web 监听端口
  servlet:
    context-path: /mock-serv

project:
  netty-port: 60001
  netty-auto-start: true
  kafka-auto-start: false