spring:
  profiles:
    active: test
  application:
    name: keepalive-server
#logging:
#  level: info
#  path: logs/
#  file: logs/listener-netty.log
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: cn.futuremove.activelink.bussiness.entity
server:
  port: 20030 # web 监听端口
  servlet:
    context-path: /mock-serv

## 其实都写死了，下面写的暂时没啥用。
project:
  auto-start:
    netty: true
    kafka: true
  netty:
    port: 60000