spring:
  profiles:
    active: @project.env@
  application:
    name: mock-gb-server
logging:
  config: classpath:log4j2-${spring.profiles.active}.xml

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: cn.futuremove.activelink.bussiness.entity
server:
  port: 10080 # web 监听端口
  servlet:
    context-path: /mock-serv

project:
  netty-port: 60001
  netty-auto-start: true
  kafka-auto-start: false
