

####
server:
  port: 8081

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: edge-server
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500


  logging:
    level:
      root: INFO
    path: ./target
    file: edge-server.log