##
## server.port = 8808
## server.servlet.context-path = /smd
server:
  port: 8808
  servlet:
    context-path: /smd

## 也可以在 VM options 中填上：
## -Dspring.output.ansi.enabled=ALWAYS
#spring:
#  output:
#    ansi:
#      enabled: ALWAYS
#
## spring.profiles.active = dev
## spring.profiles = dev
spring:
  profiles:
    active: '@project.env@'
  application:
    name: spring-mongo-demo

## 添加 ehcache.xml 配置文件的位置
## 主类上增加 @EnableCaching 注
## spring.cache.jcache.config=classpath:ehcache.xml
  cache:
    jcache:
      config: classpath*:ehcache.xml
